# Copyright (c) 2024 Arjuna Technologies, Newcastle upon Tyne. All rights reserved.

version: 2.1

jobs:
  dsbase:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layout_caching: true
      - run: |
          echo "Building"
          echo "  Repo Name: " $CIRCLE_PROJECT_REPONAME
          echo "  Branch:    " $CIRCLE_BRANCH
          echo "  Tag:       " $CIRCLE_TAG
      - run:
          command: |
              apt-get update
              apt-get install r-base-core cmake
      - run:
          command: |
              Rscript -e "install.packages('RANN', dependencies=TRUE)"
              Rscript -e "install.packages('stringr', dependencies=TRUE)"
              Rscript -e "install.packages('lme4', dependencies=TRUE)"
              Rscript -e "install.packages('dplyr', dependencies=TRUE)"
              Rscript -e "install.packages('reshape2', dependencies=TRUE)"
              Rscript -e "install.packages('polycor', dependencies=TRUE)"
              Rscript -e "install.packages('splines', dependencies=TRUE)"
              Rscript -e "install.packages('gamlss', dependencies=TRUE)"
              Rscript -e "install.packages('gamlss.dist', dependencies=TRUE)"
              Rscript -e "install.packages('mice', dependencies=TRUE)"
              Rscript -e "install.packages('childsds', dependencies=TRUE)"
workflows:
  build:
    jobs:
      - dsbase
